import { Navbar } from '@/components/Navbar'
import { TaskProvider } from '@/context/TaskContext'
import './globals.css'
import { Toaster } from './Toaster'
import { Layout } from '@/components/Layout'
import { Oswald } from 'next/font/google'

export const metadata = {
  title: 'Your Notes',
  description: 'Your Notes app, create, edit, delete notes and save in cache.Generated by create next app',
}

const oswald = Oswald({subsets:['latin']})

export default function RootLayout({ children }) {
  return (
    <html className={oswald.className} lang="en">
      <body className='bg-gradient-to-b from-zinc-800 to-zinc-950'>
        <TaskProvider>
          <Navbar />
          <Layout>
            {children}
          </Layout>
          <Toaster />
        </TaskProvider>
      </body>
    </html>
  )
}
